;
; File generated by cc65 v 2.19 - Git 3dfe03300
;
	.fopt		compiler,"cc65 v 2.19 - Git 3dfe03300"
	.setcpu		"65SC02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	on
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.dbg		file, "main.c", 1031, 1709317902
	.dbg		file, "/home/napicella/github/cc65/include/stdint.h", 6196, 1707073946
	.forceimport	__STARTUP__
	.import		_ledOff
	.import		_ledOn
	.import		_millis
	.export		_lastcalled
	.export		_current
	.export		_delay
	.export		_main

.segment	"DATA"

_lastcalled:
	.word	$0000
_current:
	.word	$0000

; ---------------------------------------------------------------
; unsigned char __near__ delay (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_delay: near

	.dbg	func, "delay", "00", static, "_delay"

.segment	"CODE"

	.dbg	line, "main.c", 14
	jsr     _millis
	sta     _current
	stx     _current+1
	.dbg	line, "main.c", 15
	lda     _current
	ldx     _current+1
	jsr     pushax
	lda     _lastcalled
	ldx     _lastcalled+1
	jsr     tossubax
	cmp     #$1A
	txa
	sbc     #$00
	lda     #$00
	ldx     #$00
	rol     a
	jeq     L0002
	.dbg	line, "main.c", 16
	lda     _current
	ldx     _current+1
	sta     _lastcalled
	stx     _lastcalled+1
	.dbg	line, "main.c", 17
	ldx     #$00
	lda     #$00
	jmp     L0001
	.dbg	line, "main.c", 19
L0002:	ldx     #$00
	lda     #$01
	jmp     L0001
	.dbg	line, "main.c", 20
L0001:	rts

	.dbg	line
.endproc

; ---------------------------------------------------------------
; void __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

	.dbg	func, "main", "00", static, "_main"
	.dbg	sym, "on", "00", auto, -1

.segment	"CODE"

	.dbg	line, "main.c", 45
	lda     #$00
	jsr     pusha
	.dbg	line, "main.c", 46
	jmp     L0007
	.dbg	line, "main.c", 47
L0002:	jsr     _delay
	cmp     #$00
	jsr     booleq
	jeq     L0007
	.dbg	line, "main.c", 48
	ldy     #$00
	ldx     #$00
	lda     (sp),y
	cmp     #$00
	jsr     booleq
	jeq     L0006
	.dbg	line, "main.c", 49
	jsr     _ledOn
	.dbg	line, "main.c", 50
	ldx     #$00
	lda     #$01
	ldy     #$00
	sta     (sp),y
	.dbg	line, "main.c", 51
	jmp     L0007
	.dbg	line, "main.c", 52
L0006:	jsr     _ledOff
	.dbg	line, "main.c", 53
	ldx     #$00
	lda     #$00
	ldy     #$00
	sta     (sp),y
	.dbg	line, "main.c", 46
L0007:	jmp     L0002
	.dbg	line, "main.c", 57
	jsr     incsp1
	rts

	.dbg	line
.endproc

