;
; File generated by cc65 v 2.19 - Git 3dfe03300
;
	.fopt		compiler,"cc65 v 2.19 - Git 3dfe03300"
	.setcpu		"65SC02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	on
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.dbg		file, "main_lcd.c", 231, 1712078205
	.dbg		file, "/home/napicella/github/cc65/include/stdint.h", 6196, 1707073946
	.forceimport	__STARTUP__
	.import		_lcd_init
	.import		_lcd_print
	.export		_main

; ---------------------------------------------------------------
; void __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

	.dbg	func, "main", "00", static, "_main"
	.dbg	sym, "str", "00", auto, -7

.segment	"CODE"

	.dbg	line, "main_lcd.c", 8
	jsr     decsp7
	ldy     #$06
L0002:	lda     M0001,y
	sta     (sp),y
	dey
	bpl     L0002
	.dbg	line, "main_lcd.c", 10
	jsr     _lcd_init
	.dbg	line, "main_lcd.c", 11
	lda     sp
	ldx     sp+1
	jsr     _lcd_print
	.dbg	line, "main_lcd.c", 12
	jsr     incsp7
	rts

	.dbg	line
.segment	"RODATA"

M0001:
	.byte	$48,$69,$20,$6D,$6F,$6D,$00

.endproc

