;
; File generated by cc65 v 2.19 - Git 3dfe03300
;
	.fopt		compiler,"cc65 v 2.19 - Git 3dfe03300"
	.setcpu		"65SC02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	on
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.dbg		file, "main_fast_call_with_param.c", 1022, 1709301858
	.dbg		file, "/home/napicella/github/cc65/include/stdint.h", 6196, 1707073946
	.forceimport	__STARTUP__
	.import		_led
	.export		_spin
	.export		_pow
	.export		_main

; ---------------------------------------------------------------
; void __near__ spin (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_spin: near

	.dbg	func, "spin", "00", static, "_spin"
	.dbg	sym, "i", "00", auto, -2
	.dbg	sym, "j", "00", auto, -4

.segment	"CODE"

	.dbg	line, "main_fast_call_with_param.c", 12
	ldx     #$00
	lda     #$00
	jsr     pushax
	.dbg	line, "main_fast_call_with_param.c", 13
	ldx     #$00
	lda     #$00
	jsr     pushax
	.dbg	line, "main_fast_call_with_param.c", 15
	jmp     L0007
	.dbg	line, "main_fast_call_with_param.c", 16
L0002:	ldy     #$02
	ldx     #$00
	lda     #$01
	jsr     addeqysp
	.dbg	line, "main_fast_call_with_param.c", 17
	jmp     L0008
	.dbg	line, "main_fast_call_with_param.c", 18
L0006:	ldy     #$00
	ldx     #$00
	lda     #$01
	jsr     addeqysp
	.dbg	line, "main_fast_call_with_param.c", 17
L0008:	ldy     #$01
	jsr     ldaxysp
	cmp     #$FF
	txa
	sbc     #$00
	bvc     L0009
	eor     #$80
L0009:	asl     a
	lda     #$00
	ldx     #$00
	rol     a
	jne     L0006
	.dbg	line, "main_fast_call_with_param.c", 15
L0007:	ldy     #$03
	jsr     ldaxysp
	cmp     #$FF
	txa
	sbc     #$00
	bvc     L0005
	eor     #$80
L0005:	asl     a
	lda     #$00
	ldx     #$00
	rol     a
	jne     L0002
	.dbg	line, "main_fast_call_with_param.c", 22
	ldx     #$00
	lda     #$00
	ldy     #$02
	jsr     staxysp
	.dbg	line, "main_fast_call_with_param.c", 23
	ldx     #$00
	lda     #$00
	ldy     #$00
	jsr     staxysp
	.dbg	line, "main_fast_call_with_param.c", 25
	jmp     L000F
	.dbg	line, "main_fast_call_with_param.c", 26
L000A:	ldy     #$02
	ldx     #$00
	lda     #$01
	jsr     addeqysp
	.dbg	line, "main_fast_call_with_param.c", 27
	jmp     L0010
	.dbg	line, "main_fast_call_with_param.c", 28
L000E:	ldy     #$00
	ldx     #$00
	lda     #$01
	jsr     addeqysp
	.dbg	line, "main_fast_call_with_param.c", 27
L0010:	ldy     #$01
	jsr     ldaxysp
	cmp     #$FF
	txa
	sbc     #$00
	bvc     L0011
	eor     #$80
L0011:	asl     a
	lda     #$00
	ldx     #$00
	rol     a
	jne     L000E
	.dbg	line, "main_fast_call_with_param.c", 25
L000F:	ldy     #$03
	jsr     ldaxysp
	cmp     #$FF
	txa
	sbc     #$00
	bvc     L000D
	eor     #$80
L000D:	asl     a
	lda     #$00
	ldx     #$00
	rol     a
	jne     L000A
	.dbg	line, "main_fast_call_with_param.c", 31
	jsr     incsp4
	rts

	.dbg	line
.endproc

; ---------------------------------------------------------------
; int __near__ pow (unsigned char x, unsigned char n)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_pow: near

	.dbg	func, "pow", "00", static, "_pow"
	.dbg	sym, "x", "00", auto, 1
	.dbg	sym, "n", "00", auto, 0
	.dbg	sym, "i", "00", auto, -1
	.dbg	sym, "number", "00", auto, -2

.segment	"CODE"

	.dbg	line, "main_fast_call_with_param.c", 34
	jsr     pusha
	.dbg	line, "main_fast_call_with_param.c", 36
	jsr     decsp1
	lda     #$01
	jsr     pusha
	.dbg	line, "main_fast_call_with_param.c", 38
	ldx     #$00
	lda     #$00
	ldy     #$01
	sta     (sp),y
L0002:	ldy     #$01
	ldx     #$00
	lda     (sp),y
	jsr     pushax
	ldy     #$04
	ldx     #$00
	lda     (sp),y
	jsr     tosultax
	jne     L0005
	jmp     L0003
	.dbg	line, "main_fast_call_with_param.c", 39
L0005:	ldy     #$00
	ldx     #$00
	lda     (sp),y
	jsr     pushax
	ldy     #$05
	ldx     #$00
	lda     (sp),y
	jsr     tosumulax
	ldy     #$00
	sta     (sp),y
	.dbg	line, "main_fast_call_with_param.c", 38
	ldy     #$01
	ldx     #$00
	clc
	lda     #$01
	adc     (sp),y
	sta     (sp),y
	jmp     L0002
	.dbg	line, "main_fast_call_with_param.c", 41
L0003:	ldy     #$00
	ldx     #$00
	lda     (sp),y
	jmp     L0001
	.dbg	line, "main_fast_call_with_param.c", 42
L0001:	jsr     incsp4
	rts

	.dbg	line
.endproc

; ---------------------------------------------------------------
; void __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

	.dbg	func, "main", "00", static, "_main"
	.dbg	sym, "i", "00", auto, -1

.segment	"CODE"

	.dbg	line, "main_fast_call_with_param.c", 45
	lda     #$00
	jsr     pusha
	.dbg	line, "main_fast_call_with_param.c", 46
	jmp     L0006
	.dbg	line, "main_fast_call_with_param.c", 47
L0002:	ldx     #$00
	lda     #$00
	ldy     #$00
	sta     (sp),y
L0005:	ldy     #$00
	ldx     #$00
	lda     (sp),y
	cmp     #$08
	jsr     boolult
	jne     L0008
	jmp     L0006
	.dbg	line, "main_fast_call_with_param.c", 49
L0008:	ldx     #$00
	lda     #$02
	jsr     pusha
	ldy     #$01
	ldx     #$00
	lda     (sp),y
	jsr     _pow
	ldx     #$00
	jsr     _led
	.dbg	line, "main_fast_call_with_param.c", 50
	jsr     _spin
	.dbg	line, "main_fast_call_with_param.c", 51
	jsr     _spin
	.dbg	line, "main_fast_call_with_param.c", 52
	jsr     _spin
	.dbg	line, "main_fast_call_with_param.c", 53
	jsr     _spin
	.dbg	line, "main_fast_call_with_param.c", 47
	ldy     #$00
	ldx     #$00
	clc
	lda     #$01
	adc     (sp),y
	sta     (sp),y
	jmp     L0005
	.dbg	line, "main_fast_call_with_param.c", 46
L0006:	jmp     L0002
	.dbg	line, "main_fast_call_with_param.c", 56
	jsr     incsp1
	rts

	.dbg	line
.endproc

