;
; File generated by cc65 v 2.19 - Git 3dfe03300
;
	.fopt		compiler,"cc65 v 2.19 - Git 3dfe03300"
	.setcpu		"65SC02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	on
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.dbg		file, "main.c", 419, 1708698682
	.forceimport	__STARTUP__
	.import		_ledOff
	.import		_ledOn
	.export		_spin
	.export		_main

; ---------------------------------------------------------------
; void __near__ spin (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_spin: near

	.dbg	func, "spin", "00", static, "_spin"
	.dbg	sym, "i", "00", auto, -2
	.dbg	sym, "j", "00", auto, -4

.segment	"CODE"

	.dbg	line, "main.c", 5
	ldx     #$00
	lda     #$00
	jsr     pushax
	.dbg	line, "main.c", 6
	ldx     #$00
	lda     #$00
	jsr     pushax
	.dbg	line, "main.c", 8
	jmp     L0007
	.dbg	line, "main.c", 9
L0002:	ldy     #$02
	ldx     #$00
	lda     #$01
	jsr     addeqysp
	.dbg	line, "main.c", 10
	jmp     L0008
	.dbg	line, "main.c", 11
L0006:	ldy     #$00
	ldx     #$00
	lda     #$01
	jsr     addeqysp
	.dbg	line, "main.c", 10
L0008:	ldy     #$01
	jsr     ldaxysp
	cmp     #$FF
	txa
	sbc     #$00
	bvc     L0009
	eor     #$80
L0009:	asl     a
	lda     #$00
	ldx     #$00
	rol     a
	jne     L0006
	.dbg	line, "main.c", 8
L0007:	ldy     #$03
	jsr     ldaxysp
	cmp     #$FF
	txa
	sbc     #$00
	bvc     L0005
	eor     #$80
L0005:	asl     a
	lda     #$00
	ldx     #$00
	rol     a
	jne     L0002
	.dbg	line, "main.c", 15
	ldx     #$00
	lda     #$00
	ldy     #$02
	jsr     staxysp
	.dbg	line, "main.c", 16
	ldx     #$00
	lda     #$00
	ldy     #$00
	jsr     staxysp
	.dbg	line, "main.c", 18
	jmp     L000F
	.dbg	line, "main.c", 19
L000A:	ldy     #$02
	ldx     #$00
	lda     #$01
	jsr     addeqysp
	.dbg	line, "main.c", 20
	jmp     L0010
	.dbg	line, "main.c", 21
L000E:	ldy     #$00
	ldx     #$00
	lda     #$01
	jsr     addeqysp
	.dbg	line, "main.c", 20
L0010:	ldy     #$01
	jsr     ldaxysp
	cmp     #$FF
	txa
	sbc     #$00
	bvc     L0011
	eor     #$80
L0011:	asl     a
	lda     #$00
	ldx     #$00
	rol     a
	jne     L000E
	.dbg	line, "main.c", 18
L000F:	ldy     #$03
	jsr     ldaxysp
	cmp     #$FF
	txa
	sbc     #$00
	bvc     L000D
	eor     #$80
L000D:	asl     a
	lda     #$00
	ldx     #$00
	rol     a
	jne     L000A
	.dbg	line, "main.c", 24
	jsr     incsp4
	rts

	.dbg	line
.endproc

; ---------------------------------------------------------------
; void __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

	.dbg	func, "main", "00", static, "_main"

.segment	"CODE"

	.dbg	line, "main.c", 28
	jsr     _ledOn
	.dbg	line, "main.c", 29
	jsr     _spin
	.dbg	line, "main.c", 30
	jsr     _ledOff
	.dbg	line, "main.c", 31
	rts

	.dbg	line
.endproc

